### ISSUE TITLE
plugin z mitingami - problemy z odświeżaniem 

### ISSUE THREAD

**Issue by napoland** [napoland/website#2]
Jest jakiś bug w interfejsie użytkownika pluginu z mitingami. 
Trzeba sprawdzić, czy jest on związany z pluginem, czy z jakimś kodem na naszej stronie.

> Własne próbowałem znaleźć miting na stronie z telefonu i ciagle pokazuje mi tylko mitingi w środę - zmiana dnia, miejsca ani pory w żaden sposób nie wpływa na wyświetlana listę.
> U was tez tak jest? Dodatkowo nawet po wpisaniu np miasta w wyszukiwarce dany miting nie chce się otworzyć. U was tez tak jest?
>

**Comment by NomenNominadum** [comment]
Chciałbym tym się zająć w pierwszej kolejności.

**Comment by napoland** [comment]
Cześć - wygląda na to, że to nasz kod powodował problemy.
Usunąłem go i wygląda na to, że teraz odświeżanie działa jak należy.
Dobrze by było się przyjrzeć dlaczego z tym tweakiem nie działa...

```
<!-- 
NA tweak - zmiana działania przycisku z lupą
zamiast menu działa jako zwykły przycisk.

<script type='text/javascript'>
jQuery(document).ready(function ($) {
	$("#mode > button").click(function() {
	  $( "#search" ).submit();
	});
});
</script>
<style>
#mode > button > span,
#mode > ul.dropdown-menu  {display: none !important;}
</style>

 -->
```

**Comment by napoland** [comment]
problemy były spowodowane pluginem Cache. 
Rozwiązaniem było wyłączenie cachu dla wszystkich urli `/meetings*`
